### ISSUE TITLE
IMHO Typo in main.js

### ISSUE THREAD

**Issue by Matt-Texier** [ClintOxx/vuetify-admin-dashboard#1]
Hi,

If I am not mistaken, there is a typo in your axios header in this line of code:

https://github.com/ClintOxx/vuetify-admin-dashboard/blob/094c2ee02a8b941f18754a46e87ed46b84b125df/src/main.js#L29

"Accept" instead of "Accepts".

It creates a CORS issue ...

Kind regards.

**Comment by ClintOxx** [comment]
@Matt-Texier thanks ill get this fixed

**Comment by ClintOxx** [comment]
Fixed
