### ISSUE TITLE
Dependency hell

### ISSUE THREAD

**Issue by jblachly** [ClintOxx/vuetify-admin-dashboard#17]
First, thank you so much for this. It was hugely helpful -- the most helpful thing I have found, actually -- in terms of bringing me to a better understanding of the (pre-build) makeup of a Vue-based SPA.

In any case, I wanted to let you know about some problems with the `packages.json` which have some implicit dependencies reflecting perhaps  global node modules installed on your system (?)

Steps to reproduce:
* Start with clean VM/OS
* Install node and npm globally in `/usr/local`
* I do have vue-cli4 installed globally as well
* No other global NPM packages
* clone the repo
* `npm install` per the quickstart
* `npm run serve` or `npm run dev` per the Quickstart

Witnesseth the warnings about unresolved peer deps eslint-*, and the failure to launch the dev server.

Unfortunately because it took me something like > 1 hour of wrangling with NPM to synchronize all dependencies (most related to eslint) I don't have a complete log. The hard part was that many items in `package.json` depend on non-current-major-version of other packages; the naive way of fixing missing dependencies by installing them unfortunately either didn't work, or broke other elements.

As an example, to fix all the eslint-* problems, one may `npm install --save-dev eslint`. However, @vue/cli-plugin-eslint is pinned at 3.12.1, which requires  `eslint-plugin-vue@4.7.1` that requires non-current-major-version of eslint (`eslint@^3.18.0 || ^4.0.0`). Thus my (perhaps naïve) conclusion that you may have older packages globally installed.

Truly I don't mean to complain, but instead just to let you know about a new user onboarding experience in hopes that this excellent resource will continue to improve.

Kind regards

**Comment by ClintOxx** [comment]
I recently just let github update the out of date dependencies without double-checking if everything was still working locally. 

That may have caused an issue, I will resume working on this soon so i will have to check it out then

**Comment by anselal** [comment]
@ClintOxx Thank you so much for your awesome work.
New to Vue.js, currently reading about vue-router and not familiar with vuex yet.

I am getting the following error when trying to run the dev server. Don't know if it is related with this issue.

![2020-01-17_10h06_27](https://user-images.githubusercontent.com/8732668/72594797-0c313480-3911-11ea-87c1-82024d27f536.png)

**Comment by anselal** [comment]
@ClintOxx shall I open a new issue on my problem starting the dev server ? Not sure if it is related to the dependencies cause I tried to checkout to an earlier commit, before you updated the dependencies and I still got the same error.
I haven't a backend yet but I followed some instructionsfrom #2 and disabled `auth`

**Comment by anselal** [comment]
@ClintOxx sorry if I am spamming this issue.
Don't know if this helps but I managed to bypass the issue following the comment at https://github.com/babel/babel-eslint/issues/681#issuecomment-420663038

**Comment by ClintOxx** [comment]
not sure if you guys are still using this or have the issue but i fixed it in the dev branch since i back to developing, feel free to reopen if you still have it
