### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by ludo1960** [ClintOxx/vuetify-admin-dashboard#2]
Hello,

Just downloaded your cool looking admin panel but I cant find any login details. Nothing in the README.txt giving details. What are the login details?

**Comment by glodov** [comment]
Do you have server-side application running?
Which one do you use?

**Comment by Matt-Texier** [comment]
You will have to adapt it to your server. On top of that token refresh needs to be updated as well. UI is waiting for a http 401 to refresh the token but in most cases you have a 401 because the token has expired ... so UI is trying to refresh an expired token which obviously doesn't work. This part have to be re-written as well ...

My 2 cents.

**Comment by ClintOxx** [comment]
@Matt-Texier I have been meaning to get around to rewriting that when i have some free time

**Comment by vanslly** [comment]
to workaround for now just set all route meta `requiresAuth: true`

**Comment by ludo1960** [comment]
Ok, thanks for that. cool looking admin!

**Comment by nezaboravi** [comment]
Hey, great things! How to solve login problem without the workaround? Any update on it?

**Comment by mzadig** [comment]
What is the login and password?

**Comment by karan-monga** [comment]
I solved the login issue with changing the path.js file (line 29) 
change 

> if (store.getters.authorized) {
to
> if (true) {

**Comment by ClintOxx** [comment]
Im going to be working on this in the next month or so now that i have a bit more free time

**Comment by anselal** [comment]
@ludo1960 the action performed when logging in is located at https://github.com/ClintOxx/vuetify-admin-dashboard/blob/master/src/store/actions.js
So you have to implement the `auth` endpoint which accepts a username and password and returns a token and a username
