### ISSUE TITLE
How to turn it into a light theme

### ISSUE THREAD

**Issue by Hydrostic** [ClintOxx/vuetify-admin-dashboard#24]

**Comment by anselal** [comment]
You can download the original light theme from creative-team

**Comment by ClintOxx** [comment]
I can add in a switch to turn it back into the light theme, right now I have it hardcoded to dark I believe

**Comment by anselal** [comment]
@Hydrostic sorry if I made you close this issue
@ClintOxx is willing to add a switch if you are interested just reopen it and comment below

thnx !!
