### ISSUE TITLE
Responsive Issues?

### ISSUE THREAD

**Issue by CoderKooke** [ClintOxx/vuetify-admin-dashboard#3]
Really want this to be good ... I too am fed up of seeing templates "supporting" Vue to only then look into the code and see jQuery.  Forked off and wanted to implement mini-variant and while it works I was finding that the part of the menu text was visible when hidden and the main content didn't line up fully.

I am going to try and resolve that but in using responsive emulator I came across the below ... do I have something wrong in the installation do you think?  This is using Chrome.

![image](https://user-images.githubusercontent.com/45196217/61002267-174f4a80-a359-11e9-9970-5a17c10d981f.png)

**Comment by thomhickey** [comment]
If I find another "Reactive", "Modern", "Responsive" framework or app or site or whatever that sneaks in jQuery I'm going to shoot myself. I loved jQuery. Loved. Sorry, I know my comment is off-topic feel free to delete it.

**Comment by ClintOxx** [comment]
@thomhickey  I actually used bulma for another project and i love it as well

@CoderKooke ill look into this soon

**Comment by ClintOxx** [comment]
This is something im stilll planning on fixing, just haven't had the free time. I got sick with Covid earlier last month and it set a lot of things back and I'm behind on everything

**Comment by thomhickey** [comment]
Glad you're feeling better, @ClintOxx

**Comment by anselal** [comment]
Feel better @ClintOxx

**Comment by ClintOxx** [comment]
thanks guys!

**Comment by ClintOxx** [comment]
Alright now that i reread this, i know of some issues with the current components so im basically in the process w=of rewriting themt o be simplier and easily updatable and using current Vuetify 2.5 or whatever assets, props and such. 

Kinda ended up rewriting a lot of this whole project, it should be in dev by the end of the week, check dev for the current version with a lot of bug fixes. The grid issue and sidebar arent fixed yet
