### ISSUE TITLE
Notification dropdown not responsive

### ISSUE THREAD

**Issue by created-by-varun** [ClintOxx/vuetify-admin-dashboard#36]
![Screenshot from 2020-10-13 00-20-50](https://user-images.githubusercontent.com/56495025/95780780-25bdac00-0cea-11eb-9149-8cec7bfc0fab.png)

**Comment by anselal** [comment]
You mean the alignment ?

**Comment by anselal** [comment]
This only happens on the demo page. If you run it locally it works fine.
I think that the demo is not updated.

@created-by-varun can you confirm that the screenshot is taken from the demo???

**Comment by created-by-varun** [comment]
Yes, I didn’t run the project locally.
The screenshot was taken from the live demo link mentioned in the repo. 
The notification drop down was overflowing outside the browser window on the right side.
