### ISSUE TITLE
Why baseURL in axios.js if you have one in main.js

### ISSUE THREAD

**Issue by UDADeveloper** [ClintOxx/vuetify-admin-dashboard#4]
Thank you for this great template. It's very helpful. I connected this template to my backend server and have a question - Why I need this in axios.js:
https://github.com/ClintOxx/vuetify-admin-dashboard/blob/ba249b7580d39a930592d7a5e0cc80f656bdd286/src/plugins/axios.js#L5

when there is one exists in line28 in main.js?

**Comment by jblachly** [comment]
Looks like plugins/axios.js is not imported but is there just for developers who prefer all plugins and plugin config grouped under `plugins/`.  Thus, is redundant but left for exemplary purposes.

**Comment by ClintOxx** [comment]
@jblachly is correct, i left it there for people who prefer their set up that way

**Comment by anselal** [comment]
@ClintOxx You can close this issue !!
