### ISSUE TITLE
login with Laravel 7 passport dont store session

### ISSUE THREAD

**Issue by alejandri** [ClintOxx/vuetify-admin-dashboard#42]
Hi I'm tryied this wonderful repo. Using Laravel Passport login I modified src/store/actions.js
When submit login form login succefully but, when navigate to other route, app redirect again to login.
Storing session not working.

     login({ commit }, userData) {
           return new Promise((resolve, reject) => {

        var config = {
        method: 'post',
        url: 'http://127.0.0.1:8000/api/login?email=alebeltran@outlook.com&password=1q2w3e4r',
        headers: {
          // ...data.getHeaders()
        },
        data: { username: userData.username, password: userData.password }
      };

      axios(config)
        .then(response => {
          const token = response.data.token
          const user = response.data.username
          console.log(response)
          // storing jwt in localStorage. https cookie is safer place to store
          localStorage.setItem('token', token)
          localStorage.setItem('user', user)
          axios.defaults.headers.common['Authorization'] = 'Bearer ' + token
          // mutation to change state properties to the values passed along
          commit('auth_success', { token, user })
          resolve(response)
        })
        .catch(err => {
          console.log('login error')
          commit('auth_error')
          localStorage.removeItem('token')
          reject(err)
        })`

**Comment by ClintOxx** [comment]
i fixed the redirect issue. it was an issue of the router nav guards in /router/index.js & paths.js
