### ISSUE TITLE
Logout router path

### ISSUE THREAD

**Issue by UDADeveloper** [ClintOxx/vuetify-admin-dashboard#5]
Logout router is working properly and sending to login form if I change this following line
https://github.com/ClintOxx/vuetify-admin-dashboard/blob/ba249b7580d39a930592d7a5e0cc80f656bdd286/src/components/core/Toolbar.vue#L109
with this:
`					this.$router.push("/");`

**Comment by AaryanAdil** [comment]
Thanks man!

**Comment by ClintOxx** [comment]
Thanks ill make this change soon
