### ISSUE TITLE
Alert menu wrong position

### ISSUE THREAD

**Issue by KevinFarrow** [ClintOxx/vuetify-admin-dashboard#6]
Windows 10
Firefox 68.0.1

when clicking on the alert bell icon, the alert menu appears off-screen to the right instead of below the icon

![___2019-08-19_10-40-43](https://user-images.githubusercontent.com/1365851/63255747-2d143180-c26e-11e9-95bf-c6a5b04b8a83.jpg)

**Comment by patrykKlimczak** [comment]
@KevinFarrow You find this bug?

**Comment by KevinFarrow** [comment]
@patrykKlimczak Not sure what you mean?

**Comment by KevinFarrow** [comment]
![2019-11-26_18-44-52](https://user-images.githubusercontent.com/1365851/69662836-fde73a80-107c-11ea-820f-eefb53446344.gif)

**Comment by ClintOxx** [comment]
Its something i been meaning to fix, will do so soon

**Comment by MiKr13** [comment]
@ClintOxx what is the status on this fix, please tell me, if you need any help, please mark it as help wanted so that we can try to fix it.

**Comment by anselal** [comment]
@MiKr13 if you can fix it please do so by creating a PR

**Comment by MiKr13** [comment]
@anselal I am on it.

**Comment by MiKr13** [comment]
@anselal @KevinFarrow @ClintOxx  There you have it. This pull request fixes the bug.
Please see this: 
![image](https://user-images.githubusercontent.com/34394719/78224535-57a5b880-74e6-11ea-99a7-730c8d0bb407.png)

**Comment by anselal** [comment]
will check it out, @MiKr13

**Comment by ClintOxx** [comment]
@MiKr13 I meant to say thanks for the pull request

**Comment by MiKr13** [comment]
> @MiKr13 I meant to say thanks for the pull request

My pleasure man, keep up the awesome work!
