### ISSUE TITLE
Footer in Maps page

### ISSUE THREAD

**Issue by UDADeveloper** [ClintOxx/vuetify-admin-dashboard#7]
Change this:
https://github.com/ClintOxx/vuetify-admin-dashboard/blob/ba249b7580d39a930592d7a5e0cc80f656bdd286/src/views/DashboardView.vue#L16

to this:
`      <core-footer v-if="$route.meta.name !== 'Maps'" />`

in order not to render footer in Maps page

**Comment by ClintOxx** [comment]
Thanks, this has been fixed via pull request
